site_name: specification v3.0 - DRAFT
docs_dir: chapters
theme: readthedocs
extra_css:
- css/style.css
use_directory_urls: true
pages:
- 'Copyright': index.md
- '1 Overview': 1-overview.md
- '2 Base Profile': 2-base-profile.md
- '3 Licensing Profile': 3-licensing-profile.md
- 'Appendix I: Creative Commons Attribution License 3.0 Unported': appendix-I-creative-commons-attribution-license-3.0-unported.md
- 'Appendix II: SPDX License Expressions': appendix-II-SPDX-license-expressions.md
- 'Appendix III: External Repository Identifiers': appendix-III-external-repository-identifiers.md
- 'Appendix IV: RDF Data Model Implementation and Identifier Syntax': appendix-IV-RDF-data-model-implementation-and-identifier-syntax.md
copyright: Copyright &copy; 2010 - 2019 Linux Foundation and its Contributors.
markdown_extensions:
    - toc:
        permalink: true
